### ISSUE TITLE
investigate uin32 indexes in dataframes

### ISSUE THREAD

**Issue by k-dominik** [ilastik/ilastikrag-fork#11]
The code seems to imply that at some time pandas might have supported uint32 indexes, which were used to save RAM:

see outdated note here:

https://github.com/ilastik/ilastikrag/blob/ef6e2425a4b9544f622d5028da2971e4c8303b7e/ilastikrag/rag.py#L336-L337

since I removed these misleading lines in #10 I opened this issue just in case we run into memory problems.

Note: I couldn't find a pandas version that supported it. Furthermore in the later merge of dataframes a new index is created anyway...

**Comment by stuarteberg** [comment]
Yeah, I was simply mistaken.  I didn't know `pandas` super well in those days... I'm sure there are plenty of things in this code which are kinda dumb.

On the other hand, the just-released pandas 2.0 [now supports other index types](https://pandas.pydata.org/docs/dev/whatsnew/v2.0.0.html#index-can-now-hold-numpy-numeric-dtypes).  So maybe I was just predicting the future... 7 years in advance.
